name: scidart_dart_interpreter
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  petitparser: ^4.2.0

dev_dependencies:
  analyzer: ^2.0.0
  pedantic: ^1.11.1
  test: ^1.17.11
  scidart_io: ^0.0.2-dev.1
